# Generated by Django 3.1.7 on 2021-03-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0002_auto_20210303_2336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studentNumber',
            new_name='student',
        ),
    ]
