# Generated by Django 3.1.7 on 2021-03-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0004_auto_20210304_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=300)),
                ('Videos', models.FileField(upload_to='video')),
            ],
        ),
    ]
