# Generated by Django 3.1.7 on 2021-03-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0005_videos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='Videos',
            new_name='Vids',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='video_name',
        ),
        migrations.AddField(
            model_name='videos',
            name='caption',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
