# Generated by Django 3.1.7 on 2021-03-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0006_auto_20210306_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='caption',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercises',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='Vids',
            field=models.FileField(upload_to='Video'),
        ),
    ]
