# Generated by Django 3.1.7 on 2021-03-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0007_auto_20210306_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='Vids',
            field=models.FileField(upload_to='videos/upload/'),
        ),
    ]
