# Generated by Django 3.1.7 on 2021-03-07 15:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0008_auto_20210307_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('file', models.FileField(upload_to='exercise')),
                ('deadline', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 7, 19, 4, 15, 697914))),
                ('score', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='exercise')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='exercises',
        ),
        migrations.DeleteModel(
            name='score',
        ),
        migrations.DeleteModel(
            name='studentNumber',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='Vids',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='caption',
        ),
        migrations.AddField(
            model_name='videos',
            name='file',
            field=models.FileField(null=True, upload_to='videos'),
        ),
        migrations.AddField(
            model_name='videos',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bp.exercise'),
        ),
    ]
