# Generated by Django 3.1.7 on 2021-03-07 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0009_auto_20210307_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 7, 19, 14, 55, 826877)),
        ),
    ]
