# Generated by Django 3.1.7 on 2021-03-07 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0013_auto_20210307_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 7, 23, 8, 57, 651685)),
        ),
    ]
